-- GoStay catalog v2: six branches, room types, room classes and pooled inventory.
-- This migration intentionally resets demo bookings and the old physical-room catalog.

UPDATE public.profiles SET branch_id = NULL WHERE branch_id IS NOT NULL;
UPDATE public.amenities
SET status = 'inactive'
WHERE name IN ('Bãi đỗ xe', 'Minibar', 'Tivi', 'Wi-Fi miễn phí', 'Wi‑Fi miễn phí');
TRUNCATE TABLE public.staff_work_sessions, public.bookings CASCADE;
DELETE FROM public.room_amenities;
DELETE FROM public.room_images;
DELETE FROM public.rooms;
DELETE FROM public.room_types;
DELETE FROM public.branches;

CREATE TABLE IF NOT EXISTS public.room_classes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name character varying NOT NULL UNIQUE,
  description text,
  sort_order integer NOT NULL DEFAULT 0,
  status character varying NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'inactive')),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

ALTER TABLE public.room_types
  ADD COLUMN IF NOT EXISTS status character varying NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'inactive'));

ALTER TABLE public.rooms
  ADD COLUMN IF NOT EXISTS room_class_id bigint REFERENCES public.room_classes(id) ON DELETE RESTRICT,
  ADD COLUMN IF NOT EXISTS inventory_count integer NOT NULL DEFAULT 1 CHECK (inventory_count > 0);

ALTER TABLE public.rooms
  ADD CONSTRAINT rooms_branch_type_class_key
  UNIQUE (branch_id, room_type_id, room_class_id);

-- Kept nullable only as a compatibility field for the current frontend/API contract.
-- Catalog v2 never writes a physical room number.
ALTER TABLE public.rooms ALTER COLUMN room_number DROP NOT NULL;
DROP INDEX IF EXISTS public.rooms_room_number_key;

ALTER TABLE public.room_classes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS room_classes_public_select ON public.room_classes;
DROP POLICY IF EXISTS room_classes_admin_all ON public.room_classes;
CREATE POLICY room_classes_public_select ON public.room_classes
  FOR SELECT TO anon, authenticated USING (status = 'active');
CREATE POLICY room_classes_admin_all ON public.room_classes
  FOR ALL TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

GRANT SELECT ON public.room_classes TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.room_classes TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.room_classes_id_seq TO authenticated;

INSERT INTO public.branches (name, address, city, phone, status) VALUES
  ('GoStay Hạ Long', 'Bãi Cháy, Hạ Long, Quảng Ninh', 'Hạ Long', '02033888888', 'active'),
  ('GoStay Nha Trang', '12 Trần Phú, Nha Trang, Khánh Hòa', 'Nha Trang', '02583888888', 'active'),
  ('GoStay Phú Quốc', 'Bãi Trường, Dương Tơ, Phú Quốc', 'Phú Quốc', '02973888888', 'active'),
  ('GoStay Hội An', 'Cửa Đại, Hội An, Quảng Nam', 'Hội An', '02353888888', 'active'),
  ('GoStay Đà Nẵng', 'Võ Nguyên Giáp, Sơn Trà, Đà Nẵng', 'Đà Nẵng', '02363888888', 'active'),
  ('GoStay Hà Nội', 'Đường Thanh Niên, Tây Hồ, Hà Nội', 'Hà Nội', '02438888888', 'active');

INSERT INTO public.room_types
  (name, description, capacity, bed_type, area_m2, base_price, status)
VALUES
  ('Classic King Room', 'Phù hợp cho hai khách với một giường đôi.', 2, '1 giường King', 28, 700000, 'active'),
  ('Classic Twin Room', 'Phù hợp cho hai khách với hai giường đơn.', 2, '2 giường đơn', 30, 750000, 'active'),
  ('Premier Triple Room', 'Phù hợp cho nhóm ba khách.', 3, '1 giường Queen và 1 giường đơn', 36, 950000, 'active'),
  ('Family Residence', 'Không gian dành cho gia đình hoặc nhóm nhỏ.', 4, '1 giường King và 2 giường đơn', 48, 1300000, 'active'),
  ('Executive Suite', 'Phòng rộng với khu vực tiếp khách riêng.', 3, '1 giường King và sofa', 55, 1600000, 'active');

INSERT INTO public.room_classes (name, description, sort_order, status) VALUES
  ('Standard', 'Tiện nghi thiết yếu, mức giá tiết kiệm.', 10, 'active'),
  ('Superior', 'Không gian và tiện nghi nâng cấp.', 20, 'active'),
  ('Deluxe', 'Nội thất cao cấp, có ban công hoặc hướng nhìn đẹp.', 30, 'active'),
  ('Premium', 'Vị trí đẹp và dịch vụ cao cấp.', 40, 'active'),
  ('Luxury', 'Hạng nghỉ dưỡng cao cấp nhất.', 50, 'active');

INSERT INTO public.rooms
  (branch_id, room_type_id, room_class_id, room_number, name, price_per_night,
   inventory_count, description, status)
SELECT
  b.id,
  rt.id,
  rc.id,
  NULL,
  CASE b.city
    WHEN 'Hạ Long' THEN CASE rt.name
      WHEN 'Classic King Room' THEN 'Azure Bay King'
      WHEN 'Classic Twin Room' THEN 'Marina Twin'
      WHEN 'Premier Triple Room' THEN 'Horizon Triple'
      WHEN 'Family Residence' THEN 'Bayfront Family Residence'
      ELSE 'Heritage Bay Suite' END
    WHEN 'Nha Trang' THEN CASE rt.name
      WHEN 'Classic King Room' THEN 'Coral King'
      WHEN 'Classic Twin Room' THEN 'Seabreeze Twin'
      WHEN 'Premier Triple Room' THEN 'Riviera Triple'
      WHEN 'Family Residence' THEN 'Coastal Family Residence'
      ELSE 'Ocean Pearl Suite' END
    WHEN 'Phú Quốc' THEN CASE rt.name
      WHEN 'Classic King Room' THEN 'Sunset King'
      WHEN 'Classic Twin Room' THEN 'Palm Garden Twin'
      WHEN 'Premier Triple Room' THEN 'Island Triple'
      WHEN 'Family Residence' THEN 'Tropical Family Residence'
      ELSE 'Pearl Coast Suite' END
    WHEN 'Đà Nẵng' THEN CASE rt.name
      WHEN 'Classic King Room' THEN 'My Khe King'
      WHEN 'Classic Twin Room' THEN 'Han River Twin'
      WHEN 'Premier Triple Room' THEN 'Son Tra Triple'
      WHEN 'Family Residence' THEN 'Danang Family Retreat'
      ELSE 'Marble Mountain Suite' END
    WHEN 'Hà Nội' THEN CASE rt.name
      WHEN 'Classic King Room' THEN 'West Lake King'
      WHEN 'Classic Twin Room' THEN 'Old Quarter Twin'
      WHEN 'Premier Triple Room' THEN 'Red River Triple'
      WHEN 'Family Residence' THEN 'Capital Family Residence'
      ELSE 'Imperial Suite' END
    ELSE CASE rt.name
      WHEN 'Classic King Room' THEN 'Lantern King'
      WHEN 'Classic Twin Room' THEN 'Heritage Twin'
      WHEN 'Premier Triple Room' THEN 'Riverside Triple'
      WHEN 'Family Residence' THEN 'Ancient Town Family Residence'
      ELSE 'Silk Road Suite' END
  END,
  CASE rc.name
    WHEN 'Standard' THEN rt.base_price
    WHEN 'Superior' THEN (rt.base_price * 1.15)::bigint
    WHEN 'Deluxe' THEN (rt.base_price * 1.35)::bigint
    WHEN 'Premium' THEN (rt.base_price * 1.60)::bigint
    ELSE (rt.base_price * 2.00)::bigint
  END,
  CASE rc.name WHEN 'Luxury' THEN 2 WHEN 'Premium' THEN 3 ELSE 5 END,
  rt.description || ' Hạng ' || rc.name || ' tại ' || b.name || '.',
  'available'
FROM public.branches b
CROSS JOIN public.room_types rt
CROSS JOIN public.room_classes rc
WHERE NOT (rt.name = 'Premier Triple Room' AND rc.name IN ('Premium', 'Luxury'));

CREATE OR REPLACE FUNCTION public.search_available_rooms(
  p_check_in_date date,
  p_check_out_date date,
  p_guests integer,
  p_branch_id bigint DEFAULT NULL,
  p_room_type_id bigint DEFAULT NULL,
  p_min_price bigint DEFAULT NULL,
  p_max_price bigint DEFAULT NULL
)
RETURNS TABLE (
  room_id bigint, branch_id bigint, branch_name character varying,
  branch_city character varying, room_type_id bigint,
  room_type_name character varying, room_type_capacity integer,
  room_type_bed_type character varying, room_type_area_m2 numeric,
  room_number character varying, room_name character varying,
  room_description text, price_per_night bigint, image_url text,
  image_alt_text character varying
)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = ''
AS $function$
BEGIN
  IF p_check_in_date IS NULL OR p_check_out_date IS NULL
     OR p_check_out_date <= p_check_in_date OR p_check_in_date < CURRENT_DATE THEN
    RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'The availability date range is invalid.';
  END IF;
  IF p_guests IS NULL OR p_guests < 1 THEN
    RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'The guest count is invalid.';
  END IF;

  RETURN QUERY
  SELECT r.id, b.id, b.name, b.city, rt.id,
    (rt.name || ' - ' || rc.name)::character varying, rt.capacity,
    rt.bed_type, rt.area_m2, NULL::character varying, r.name, r.description,
    r.price_per_night, img.image_url, img.alt_text
  FROM public.rooms r
  JOIN public.branches b ON b.id = r.branch_id
  JOIN public.room_types rt ON rt.id = r.room_type_id
  JOIN public.room_classes rc ON rc.id = r.room_class_id
  LEFT JOIN LATERAL (
    SELECT ri.image_url, ri.alt_text FROM public.room_images ri
    WHERE ri.room_id = r.id
    ORDER BY ri.is_primary DESC, ri.sort_order, ri.id LIMIT 1
  ) img ON true
  WHERE r.status = 'available' AND b.status = 'active'
    AND rt.status = 'active' AND rc.status = 'active'
    AND rt.capacity >= p_guests
    AND (p_branch_id IS NULL OR r.branch_id = p_branch_id)
    AND (p_room_type_id IS NULL OR r.room_type_id = p_room_type_id)
    AND (p_min_price IS NULL OR r.price_per_night >= p_min_price)
    AND (p_max_price IS NULL OR r.price_per_night <= p_max_price)
    AND (SELECT count(*) FROM public.bookings bk
         WHERE bk.room_id = r.id
           AND bk.booking_status IN ('pending', 'confirmed', 'checked_in')
           AND bk.check_in_date < p_check_out_date
           AND bk.check_out_date > p_check_in_date) < r.inventory_count
  ORDER BY r.price_per_night, b.id, rt.id, rc.sort_order, r.id;
END;
$function$;

ALTER TABLE public.bookings DROP CONSTRAINT IF EXISTS bookings_no_holding_overlap;

CREATE OR REPLACE FUNCTION public.create_booking(
  p_room_id bigint, p_check_in_date date, p_check_out_date date,
  p_number_of_guests integer, p_guest_name text, p_guest_email text,
  p_guest_phone text, p_special_request text DEFAULT NULL
)
RETURNS TABLE (
  booking_id uuid, booking_code character varying,
  booking_status character varying, payment_status character varying,
  total_amount bigint, created_at timestamp with time zone
)
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path = ''
AS $function$
DECLARE
  v_user uuid := auth.uid();
  v_status character varying;
  v_price bigint;
  v_capacity integer;
  v_inventory integer;
  v_held integer;
  v_nights integer;
  v_subtotal bigint;
  v_tax bigint;
  v_total bigint;
  v_id uuid := pg_catalog.gen_random_uuid();
  v_now timestamp with time zone := pg_catalog.statement_timestamp();
  v_code character varying;
BEGIN
  IF v_user IS NULL THEN
    RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'Authentication is required to create a booking.';
  END IF;
  SELECT p.status INTO v_status FROM public.profiles p WHERE p.id = v_user;
  IF v_status IS DISTINCT FROM 'active' THEN
    RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'The authenticated profile is not allowed to create bookings.';
  END IF;
  IF p_check_in_date IS NULL OR p_check_out_date <= p_check_in_date
     OR p_check_in_date < CURRENT_DATE OR p_number_of_guests < 1 THEN
    RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'The booking input is invalid.';
  END IF;

  SELECT r.price_per_night, rt.capacity, r.inventory_count
  INTO v_price, v_capacity, v_inventory
  FROM public.rooms r
  JOIN public.branches b ON b.id = r.branch_id AND b.status = 'active'
  JOIN public.room_types rt ON rt.id = r.room_type_id AND rt.status = 'active'
  JOIN public.room_classes rc ON rc.id = r.room_class_id AND rc.status = 'active'
  WHERE r.id = p_room_id AND r.status = 'available'
  FOR UPDATE OF r;
  IF NOT FOUND THEN
    RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'The selected room is not available for booking.';
  END IF;
  IF p_number_of_guests > v_capacity THEN
    RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'The guest count exceeds the selected room capacity.';
  END IF;

  SELECT count(*) INTO v_held FROM public.bookings bk
  WHERE bk.room_id = p_room_id
    AND bk.booking_status IN ('pending', 'confirmed', 'checked_in')
    AND bk.check_in_date < p_check_out_date
    AND bk.check_out_date > p_check_in_date;
  IF v_held >= v_inventory THEN
    RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'The selected room class is sold out for those dates.';
  END IF;

  v_nights := p_check_out_date - p_check_in_date;
  v_subtotal := v_price * v_nights;
  v_tax := pg_catalog.round(v_subtotal::numeric * 0.10)::bigint;
  v_total := v_subtotal + v_tax;
  v_code := 'GS' || pg_catalog.to_char(v_now, 'YYYYMMDD') || '-' ||
    pg_catalog.upper(pg_catalog.substr(pg_catalog.replace(v_id::text, '-', ''), 1, 12));

  INSERT INTO public.bookings (
    id, booking_code, user_id, room_id, guest_name, guest_email, guest_phone,
    check_in_date, check_out_date, number_of_nights, number_of_guests,
    special_request, price_per_night, subtotal, tax_rate, tax_amount,
    discount_amount, total_amount, booking_status, payment_method,
    payment_status, created_at, updated_at, cancelled_at, promotion_id
  ) VALUES (
    v_id, v_code, v_user, p_room_id, pg_catalog.btrim(p_guest_name),
    pg_catalog.btrim(p_guest_email), pg_catalog.btrim(p_guest_phone),
    p_check_in_date, p_check_out_date, v_nights, p_number_of_guests,
    nullif(pg_catalog.btrim(p_special_request), ''), v_price, v_subtotal,
    10, v_tax, 0, v_total, 'pending', 'pay_at_hotel', 'unpaid',
    v_now, v_now, NULL, NULL
  );
  RETURN QUERY SELECT v_id, v_code, 'pending'::character varying,
    'unpaid'::character varying, v_total, v_now;
END;
$function$;
